### PR TITLE
[FIX] Copying file issue

### LINKED ISSUE #1374: Cannot copy a file in a subfolder from a S3MultiLevelDataProvider to a UserkeyFlatDirSshDataProvider
When trying to copy a file that was register from a S3MultiLevelDataProvider in a subfolder: 

`sub123/abc.txt`

to a UserkeyFlatDirSshDataProvider I have a strange error message: 

```
[2024-02-13 18:21:10 UTC] For 1 file, Did not get a proper numeric ID? Got: 'nil'.:
abc.txt
```

and the copy is not performed.

### PR DESCRIPTION
**Pull request by natacha-beck**
[FIX] issue when copying file from DP with browse capablity to one th…at do not have it

Fixed #1374

### CODE REVIEW

File: BrainPortal/app/models/data_provider.rb [hunk 1]
```diff
@@ -859,6 +859,8 @@ def provider_copy_to_otherprovider(userfile, otherprovider, options = {})
     newfile.created_at       = Time.now      unless target_exists
     newfile.updated_at       = Time.now
     newfile.immutable        = false
+    # Check if DP has_browse_path_capabilities? if not, set browse_path to nil
+    newfile.browse_path     = nil if !DataProvider.find(otherprovider.id).has_browse_path_capabilities?
```
Comment (prioux) [inline BrainPortal/app/models/data_provider.rb:863]: Why do `DataProvider.find(otherprovider.id)` ?!? Isn't that ridiculous?

Comment (natacha-beck) [reply BrainPortal/app/models/data_provider.rb]: Indeed it is.
