### PR TITLE
Fixes in behaviour when CSRF token is wrong

### LINKED ISSUE #477: CSRF check failures can redirect to a POST
If a POST is performed with a bad CSRF, the session records the original page to `:return_to` and the user is returned to the login page. When authenticating successfully, the `:return_to` is sent as a GET redirect, which fails.

To test:

* Go to userfiles index page
* In the console, find the current session object under `CbrainSession`, and change in its `data` the value of the key `"_csrf_token"`.
* Do an action that triggers a POST (such as select a file to compress or uncompress
* You'll be redirected to the login page
* Enter login password
* You'll be redirected to a wrong URL (e.g. `/userfiles/uncompress`)

### PR DESCRIPTION
**Pull request by crocodoyle**
Prevents a user from logging in when they had a bad CSRF token.
When a session is invalid due to a bad CSRF token, a user logs back in again, and is returned to the page that triggered the logout. This can no longer be a POST.

Fixes #477 and #478.

### CODE REVIEW

File: BrainPortal/app/controllers/sessions_controller.rb [hunk 1]
```diff
@@ -51,8 +51,16 @@ def new #:nodoc:
   end
 
   def create #:nodoc:
-    user = User.authenticate(params[:login], params[:password]) # can be nil if it fails
-    create_from_user(user)
+    # If the csrf token is blank, it was reset by Rails' request forgery protection
+    # and we want to prevent login
+    if current_session["_csrf_token"]
```
Comment (prioux) [inline BrainPortal/app/controllers/sessions_controller.rb]: That doesn't seem right, this test only verify that the token exists... ? Let me try it first...

**Comment by crocodoyle** [comment]
This broke a few tests for SessionController.
